### ISSUE TITLE
I cannot see logo changes neither in Console nor Enduser

### ISSUE THREAD

**Issue by ilgrosso** [OmidZare1991/apache-syncope#2]
After starting your project from sources via

```
mvn -Pall clean install
cd enduser
mvn -Pembedded,all
```

I am accessing http://localhost:9080/syncope-console/ and seeing the standard Syncope logo both in login form and internal pages.

I am also accessing http://localhost:9080/syncope-enduser/ and seeing the the standard Syncope logo in the login form.

**Comment by OmidZare1991** [comment]
logo changes successfully done.

**Comment by OmidZare1991** [comment]
![enduser logo](https://user-images.githubusercontent.com/97349246/150558734-be0fb482-7d71-4ebf-bd6e-c7f6af55a6f6.PNG)
![logo](https://user-images.githubusercontent.com/97349246/150558741-e95528f7-9dbc-4446-9bb3-2efa6a1150ad.png)
![login login](https://user-images.githubusercontent.com/97349246/150558743-322114d3-a468-4142-a831-6cfb19797640.PNG)

**Comment by ilgrosso** [comment]
I confirm it works now.
