### ISSUE TITLE
REST endpoint does not return JSON

### ISSUE THREAD

**Issue by ilgrosso** [OmidZare1991/apache-syncope#3]
I was able to see the new REST endpoint.

The payload returned is not JSON; in fact, Swagger returns:

![image](https://user-images.githubusercontent.com/1064664/150292107-918015d1-8fa7-44d8-8645-4b991d2b7312.png)

Moreover, the new endpoint is also declaring to be able to return JSON, XML or YAML - as many other Syncope endpoints; however, this was not required by your exercise.

**Comment by OmidZare1991** [comment]
![new rest endpoint](https://user-images.githubusercontent.com/97349246/150557836-17b72d5d-4bf5-4834-8277-eaf6268be082.PNG)

the tag name in swagger changed to Info

successfully done

**Comment by OmidZare1991** [comment]
The rest endpoint tag changed  to “Info”  in swagger. 

Rest endpoint url as shown in postman image:
syncope/rest/info/response

**Comment by ilgrosso** [comment]
I confirm it works now.
